rmtrash: add safe `rm` command

diff --git a/utils/rmtrash b/utils/rmtrash
--- a/utils/rmtrash
+++ b/utils/rmtrash
@@ -234,209 +234,209 @@ fi
 eval set -- "$OPTIONS"
 
 # default option values
-FORCE=false				# -f / --force                          boolean
-INTERACTIVE="default"	# -i / -I / --interactive               string ( default / never / once / always )
-ONE_FILE_SYSTEM=false	# --one-file-system                     boolean
-PRESERVE_ROOT=true		# --preserve-root / --no-preserve-root  boolean
-RMDIR_MODE=false		# -d / --dir                            boolean
-RECURSIVE=false			# -r / -R / --recursive                 boolean
-VERBOSE=false			# -v / --verbose                        boolean
-FORBID_ROOT="never" 	# --forbid-root                         string ( always / ask-forbid / ask-pass / pass / never )
+FORCE=false           # -f / --force                          boolean
+INTERACTIVE="default" # -i / -I / --interactive               string ( default / never / once / always )
+ONE_FILE_SYSTEM=false # --one-file-system                     boolean
+PRESERVE_ROOT=true    # --preserve-root / --no-preserve-root  boolean
+RMDIR_MODE=false      # -d / --dir                            boolean
+RECURSIVE=false       # -r / -R / --recursive                 boolean
+VERBOSE=false         # -v / --verbose                        boolean
+FORBID_ROOT="never"   # --forbid-root                         string ( always / ask-forbid / ask-pass / pass / never )
 
 # parse options
 while true; do
 	case "$1" in
-		"-f"|"--force")
-			FORCE=true
-			INTERACTIVE="never"
-			shift
-			;;
+	"-f" | "--force")
+		FORCE=true
+		INTERACTIVE="never"
+		shift
+		;;
 
-		"-i"|"-I"|"--interactive")
-			FORCE=false
+	"-i" | "-I" | "--interactive")
+		FORCE=false
 
-			if [ "$1" == "--interactive" ]; then
-				if [ "$2" == "never" ] || [ "$2" == "no" ] || [ "$2" == "none" ]; then
-					INTERACTIVE="never"
-				elif [ "$2" == "once" ]; then
-					INTERACTIVE="once"
-				elif [ "$2" == "always" ] || [ "$2" == "yes" ] || [ -z "$2" ]; then
-					INTERACTIVE="always"
-				else
-					echo "$APP_NAME: invalid argument '$2' for '--interactive'" >&2
-					echo "Valid arguments are:" >&2
-					echo "  - 'never', 'no', 'none'" >&2
-					echo "  - 'once'" >&2
-					echo "  - 'always', 'yes'" >&2
-					echo "Try \`$APP_NAME --help\` for more information." >&2
-					exit 2
-				fi
-
-				shift 2
+		if [ "$1" == "--interactive" ]; then
+			if [ "$2" == "never" ] || [ "$2" == "no" ] || [ "$2" == "none" ]; then
+				INTERACTIVE="never"
+			elif [ "$2" == "once" ]; then
+				INTERACTIVE="once"
+			elif [ "$2" == "always" ] || [ "$2" == "yes" ] || [ -z "$2" ]; then
+				INTERACTIVE="always"
 			else
-				if [ "$1" == "-I" ]; then
-					INTERACTIVE="once"
-				else
-					INTERACTIVE="always"
-				fi
-
-				shift
-			fi
-			;;
-
-		"--one-file-system")
-			ONE_FILE_SYSTEM=true
-			shift
-			;;
-
-		"--preserve-root")
-			PRESERVE_ROOT=true
-			shift
-			;;
-
-		"--no-preserve-root")
-			PRESERVE_ROOT=false
-			shift
-			;;
-
-		"-d"|"--dir")
-			RECURSIVE=false
-			RMDIR_MODE=true
-			shift
-			;;
-
-		"-r"|"-R"|"--recursive")
-			RECURSIVE=true
-			RMDIR_MODE=false
-			shift
-			;;
-
-		"-v"|"--verbose")
-			VERBOSE=true
-			shift
-			;;
-
-		"--forbid-root")
-			if [ "$2" == "always" ] || [ "$2" == "yes" ]; then
-				FORBID_ROOT="always"
-			elif [ "$2" == "ask-forbid" ] || [ -z "$2" ]; then
-				FORBID_ROOT="ask-forbid"
-			elif [ "$2" == "ask-pass" ]; then
-				FORBID_ROOT="ask-pass"
-			elif [ "$2" == "pass" ]; then
-				FORBID_ROOT="pass"
-			elif [ "$2" == "never" ] || [ "$2" == "no" ]; then
-				FORBID_ROOT="never"
-			else
-				echo "$APP_NAME: invalid argument '$2' for '--forbid-root'" >&2
+				echo "$APP_NAME: invalid argument '$2' for '--interactive'" >&2
 				echo "Valid arguments are:" >&2
+				echo "  - 'never', 'no', 'none'" >&2
+				echo "  - 'once'" >&2
 				echo "  - 'always', 'yes'" >&2
-				echo "  - 'ask-forbid'" >&2
-				echo "  - 'ask-pass'" >&2
-				echo "  - 'pass'" >&2
-				echo "  - 'never', 'no'" >&2
 				echo "Try \`$APP_NAME --help\` for more information." >&2
 				exit 2
 			fi
 
 			shift 2
-			;;
+		else
+			if [ "$1" == "-I" ]; then
+				INTERACTIVE="once"
+			else
+				INTERACTIVE="always"
+			fi
 
-		"--forbid-root-force")
-			# backward compatibility
+			shift
+		fi
+		;;
+
+	"--one-file-system")
+		ONE_FILE_SYSTEM=true
+		shift
+		;;
+
+	"--preserve-root")
+		PRESERVE_ROOT=true
+		shift
+		;;
+
+	"--no-preserve-root")
+		PRESERVE_ROOT=false
+		shift
+		;;
+
+	"-d" | "--dir")
+		RECURSIVE=false
+		RMDIR_MODE=true
+		shift
+		;;
+
+	"-r" | "-R" | "--recursive")
+		RECURSIVE=true
+		RMDIR_MODE=false
+		shift
+		;;
+
+	"-v" | "--verbose")
+		VERBOSE=true
+		shift
+		;;
+
+	"--forbid-root")
+		if [ "$2" == "always" ] || [ "$2" == "yes" ]; then
+			FORBID_ROOT="always"
+		elif [ "$2" == "ask-forbid" ] || [ -z "$2" ]; then
+			FORBID_ROOT="ask-forbid"
+		elif [ "$2" == "ask-pass" ]; then
+			FORBID_ROOT="ask-pass"
+		elif [ "$2" == "pass" ]; then
 			FORBID_ROOT="pass"
-			shift
-			;;
-
-		"--help")
-			TRASH_CMD_NAME="$(basename "$TRASH_CMD")"
-
-			showUsage
-			echo
-			echo "Put files (and directories) in trash using the \`$TRASH_CMD_NAME\` command in a way"
-			echo "that is, otherwise as \`$TRASH_CMD_NAME\` itself, compatible to GNUs \`rm\`."
-			echo "  see $RM_CMD --help"
-			echo "  see $TRASH_CMD --help"
-			echo
-			echo "Help options:"
-			echo "      --help                display this help and exit"
-			echo "      --version             output version information and exit"
-			echo
-			echo "Application options:"
-			echo "  -f, --force               ignore nonexistent files, never prompt"
-			echo "  -i                        prompt before every removal"
-			echo "  -I                        prompt once before removing more than three files,"
-			echo "                              or when removing recursively.  Less intrusive"
-			echo "                              than -i, while still giving protection against"
-			echo "                              most mistakes"
-			echo "      --interactive[=WHEN]  prompt according to WHEN: never, once (-I), or"
-			echo "                              always (-i).  Without WHEN, prompt always"
-			echo "      --one-file-system     when removing a hierarchy recursively, skip any"
-			echo "                              directory that is on a file system different"
-			echo "                              from that of the corresponding command line"
-			echo "                              argument"
-			echo "      --no-preserve-root    do not treat '/' specially"
-			echo "      --preserve-root       do not remove '/' (default)"
-			echo "  -r, -R, --recursive       remove directories and their contents recursively"
-			echo "  -d, --dir                 remove empty directories"
-			echo "  -v, --verbose             explain what is being done"
-			echo
-			echo "Replacement option:"
-			echo "  This option is not supposed to be used when calling $APP_NAME, it helps you"
-			echo "  to control how and in which cases \`rm\` is replaced.  If you don't set this"
-			echo "  option, root isn't treated specially."
-			echo "      --forbid-root[=HOW]   forbid user root to trash files.  When standard"
-			echo "                              input is a terminal, 'ask-forbid' and 'ask-pass'"
-			echo "                              will question the user to pass the command to"
-			echo "                              \`$RM_CMD\`. When standard input is no terminal,"
-			echo "                              'ask-forbid' will abort the command, whereas"
-			echo "                              'ask-pass' will pass the command to \`$RM_CMD\`."
-			echo "                              Use 'pass' to pass all commands of user root to"
-			echo "                              \`$RM_CMD\`. If user root should never trash"
-			echo "                              files, use 'always'. In contrast, 'never' treats"
-			echo "                              root in no special way. Without HOW,"
-			echo "                              'ask-forbid' is assumed"
-			echo
-			echo "By default, $APP_NAME does not remove directories.  Use the --recursive"
-			echo "(-r or -R) option to remove each listed directory, too, along with all of"
-			echo "its contents."
-			echo
-			echo "To remove a file whose name starts with a '-', for example '-foo', use one"
-			echo "of these commands:"
-			echo "  $APP_NAME -- -foo"
-			echo "  $APP_NAME ./-foo"
-			echo
-			echo "See also \`trash-list\` (or \`list-trash\`), \`trash-empty\` (or \`empty-trash\`),"
-			echo "\`trash-restore\` (or \`restore-trash\`), \`trash-rm\`, and the FreeDesktop.org"
-			echo "Trash Specification at <http://www.ramendik.ru/docs/trashspec.html>."
-			echo
-			echo "Please report bugs using GitHub at <https://github.com/PhrozenByte/rmtrash>."
-			echo "Besides, you will find general help and information about $APP_NAME there."
-			exit 0
-			;;
-
-		"--version")
-			echo "rmtrash $VERSION (build $BUILD)"
-			echo "Copyright (C) 2011-2020 Daniel Rudolf"
-			echo "License GPLv3: GNU GPL version 3 only <http://gnu.org/licenses/gpl.html>."
-			echo "This is free software: you are free to change and redistribute it."
-			echo "There is NO WARRANTY, to the extent permitted by law."
-			echo
-			echo "Written by Daniel Rudolf <https://www.daniel-rudolf.de/>"
-			echo "See also: <https://github.com/PhrozenByte/rmtrash>"
-			exit 0
-			;;
-
-		"--")
-			shift
-			break
-			;;
-
-		*)
-			showUsage
-			echo "$APP_NAME: execution of getopt failed" >&2
+		elif [ "$2" == "never" ] || [ "$2" == "no" ]; then
+			FORBID_ROOT="never"
+		else
+			echo "$APP_NAME: invalid argument '$2' for '--forbid-root'" >&2
+			echo "Valid arguments are:" >&2
+			echo "  - 'always', 'yes'" >&2
+			echo "  - 'ask-forbid'" >&2
+			echo "  - 'ask-pass'" >&2
+			echo "  - 'pass'" >&2
+			echo "  - 'never', 'no'" >&2
+			echo "Try \`$APP_NAME --help\` for more information." >&2
 			exit 2
-			;;
+		fi
+
+		shift 2
+		;;
+
+	"--forbid-root-force")
+		# backward compatibility
+		FORBID_ROOT="pass"
+		shift
+		;;
+
+	"--help")
+		TRASH_CMD_NAME="$(basename "$TRASH_CMD")"
+
+		showUsage
+		echo
+		echo "Put files (and directories) in trash using the \`$TRASH_CMD_NAME\` command in a way"
+		echo "that is, otherwise as \`$TRASH_CMD_NAME\` itself, compatible to GNUs \`rm\`."
+		echo "  see $RM_CMD --help"
+		echo "  see $TRASH_CMD --help"
+		echo
+		echo "Help options:"
+		echo "      --help                display this help and exit"
+		echo "      --version             output version information and exit"
+		echo
+		echo "Application options:"
+		echo "  -f, --force               ignore nonexistent files, never prompt"
+		echo "  -i                        prompt before every removal"
+		echo "  -I                        prompt once before removing more than three files,"
+		echo "                              or when removing recursively.  Less intrusive"
+		echo "                              than -i, while still giving protection against"
+		echo "                              most mistakes"
+		echo "      --interactive[=WHEN]  prompt according to WHEN: never, once (-I), or"
+		echo "                              always (-i).  Without WHEN, prompt always"
+		echo "      --one-file-system     when removing a hierarchy recursively, skip any"
+		echo "                              directory that is on a file system different"
+		echo "                              from that of the corresponding command line"
+		echo "                              argument"
+		echo "      --no-preserve-root    do not treat '/' specially"
+		echo "      --preserve-root       do not remove '/' (default)"
+		echo "  -r, -R, --recursive       remove directories and their contents recursively"
+		echo "  -d, --dir                 remove empty directories"
+		echo "  -v, --verbose             explain what is being done"
+		echo
+		echo "Replacement option:"
+		echo "  This option is not supposed to be used when calling $APP_NAME, it helps you"
+		echo "  to control how and in which cases \`rm\` is replaced.  If you don't set this"
+		echo "  option, root isn't treated specially."
+		echo "      --forbid-root[=HOW]   forbid user root to trash files.  When standard"
+		echo "                              input is a terminal, 'ask-forbid' and 'ask-pass'"
+		echo "                              will question the user to pass the command to"
+		echo "                              \`$RM_CMD\`. When standard input is no terminal,"
+		echo "                              'ask-forbid' will abort the command, whereas"
+		echo "                              'ask-pass' will pass the command to \`$RM_CMD\`."
+		echo "                              Use 'pass' to pass all commands of user root to"
+		echo "                              \`$RM_CMD\`. If user root should never trash"
+		echo "                              files, use 'always'. In contrast, 'never' treats"
+		echo "                              root in no special way. Without HOW,"
+		echo "                              'ask-forbid' is assumed"
+		echo
+		echo "By default, $APP_NAME does not remove directories.  Use the --recursive"
+		echo "(-r or -R) option to remove each listed directory, too, along with all of"
+		echo "its contents."
+		echo
+		echo "To remove a file whose name starts with a '-', for example '-foo', use one"
+		echo "of these commands:"
+		echo "  $APP_NAME -- -foo"
+		echo "  $APP_NAME ./-foo"
+		echo
+		echo "See also \`trash-list\` (or \`list-trash\`), \`trash-empty\` (or \`empty-trash\`),"
+		echo "\`trash-restore\` (or \`restore-trash\`), \`trash-rm\`, and the FreeDesktop.org"
+		echo "Trash Specification at <http://www.ramendik.ru/docs/trashspec.html>."
+		echo
+		echo "Please report bugs using GitHub at <https://github.com/PhrozenByte/rmtrash>."
+		echo "Besides, you will find general help and information about $APP_NAME there."
+		exit 0
+		;;
+
+	"--version")
+		echo "rmtrash $VERSION (build $BUILD)"
+		echo "Copyright (C) 2011-2020 Daniel Rudolf"
+		echo "License GPLv3: GNU GPL version 3 only <http://gnu.org/licenses/gpl.html>."
+		echo "This is free software: you are free to change and redistribute it."
+		echo "There is NO WARRANTY, to the extent permitted by law."
+		echo
+		echo "Written by Daniel Rudolf <https://www.daniel-rudolf.de/>"
+		echo "See also: <https://github.com/PhrozenByte/rmtrash>"
+		exit 0
+		;;
+
+	"--")
+		shift
+		break
+		;;
+
+	*)
+		showUsage
+		echo "$APP_NAME: execution of getopt failed" >&2
+		exit 2
+		;;
 	esac
 done
 
@@ -487,7 +487,7 @@ if [ "$FORBID_ROOT" != "never" ] && [ "$(id -u)" -eq 0 ]; then
 
 			CMD_ARGUMENTS=()
 			while [ $# -gt 0 ]; do
-				CMD_ARGUMENTS+=( "$1" )
+				CMD_ARGUMENTS+=("$1")
 				shift
 			done
 
@@ -548,7 +548,7 @@ if [ $# -gt 1 ]; then
 		# get return value
 		EXIT_STATUS=$?
 		if [ $EXIT_STATUS -ne 0 ]; then
-			EXIT=$(( $EXIT | $EXIT_STATUS ))
+			EXIT=$(($EXIT | $EXIT_STATUS))
 		fi
 
 		# process the next argument
@@ -623,14 +623,14 @@ while [ $INDEX -lt $MAX ]; do
 		if [ $RMDIR_MODE == true ]; then
 			if [ -z "$(find "$ARGUMENT" -maxdepth 0 -empty)" ]; then
 				echo "$APP_NAME: cannot remove '$ARGUMENT': Directory not empty" >&2
-				EXIT=$(( $EXIT | 512 ))
+				EXIT=$(($EXIT | 512))
 				let "INDEX++"
 				continue
 			fi
 
 		elif [ $RECURSIVE == false ]; then
 			echo "$APP_NAME: cannot remove '$FILENAME': Is a directory" >&2
-			EXIT=$(( $EXIT | 512 ))
+			EXIT=$(($EXIT | 512))
 			let "INDEX++"
 			continue
 
@@ -838,7 +838,7 @@ while [ $INDEX -lt $MAX ]; do
 					let "DELETE_FILES_INDEX++"
 				done
 
-				declare -a DELETE_FILES=( "${NEW_DELETE_FILES[@]}" )
+				declare -a DELETE_FILES=("${NEW_DELETE_FILES[@]}")
 				unset NEW_DELETE_FILES
 
 				# add the descended directory instead
@@ -857,7 +857,7 @@ while [ $INDEX -lt $MAX ]; do
 				let "DESCENDED_DIRECTORIES_INDEX++"
 			done
 
-			declare -a DESCENDED_DIRECTORIES=( "${NEW_DESCENDED_DIRECTORIES[@]}" )
+			declare -a DESCENDED_DIRECTORIES=("${NEW_DESCENDED_DIRECTORIES[@]}")
 			unset NEW_DESCENDED_DIRECTORIES
 		fi
 	done
@@ -878,7 +878,7 @@ if [ ${#DELETE_FILES[@]} -gt 0 ]; then
 	MAX=${#DELETE_FILES[@]}
 	CMD_ARGUMENTS=()
 	while [ $INDEX -lt $MAX ]; do
-		CMD_ARGUMENTS+=( "${DELETE_FILES[$INDEX]}" )
+		CMD_ARGUMENTS+=("${DELETE_FILES[$INDEX]}")
 		let "INDEX++"
 	done
 
@@ -955,7 +955,7 @@ if [ ${#DELETE_FILES[@]} -gt 0 ]; then
 
 					# output what actually happened
 					echo "$APP_NAME: cannot remove '$DELETE_ARGUMENT': unable to create trashcan '$INSUFFICIENT_TRASHCAN': Permission denied" >&2
-					EXIT=$(( $EXIT | 1024 ))
+					EXIT=$(($EXIT | 1024))
 
 					# recommend user to create a trashcan-base-directory
 					INSUFFICIENT_TRASHCAN_BASE_DIRECTORY="$(echo "$INSUFFICIENT_TRASHCAN" | grep -m 1 -oP "^([^\0]+?).Trash(?=-$(id -u)$)")"
@@ -986,7 +986,7 @@ if [ ${#DELETE_FILES[@]} -gt 0 ]; then
 							RM_EXIT_STATUS=$?
 
 							if [ "$RM_EXIT_STATUS" -ne 0 ]; then
-								EXIT=$(( $EXIT | 16 ))
+								EXIT=$(($EXIT | 16))
 								echo "$APP_NAME: execution of \`$RM_CMD\` failed (exit status $RM_EXIT_STATUS)" >&2
 							fi
 						fi
@@ -1020,7 +1020,7 @@ if [ ${#DELETE_FILES[@]} -gt 0 ]; then
 
 				# output what actually happened
 				echo "$APP_NAME: cannot remove '$DELETE_ARGUMENT': you can't trash the trashcan" >&2
-				EXIT=$(( $EXIT | 2048 ))
+				EXIT=$(($EXIT | 2048))
 
 				# ask to pass argument to rm if shell is in interactive mode
 				if [ $SHELL_IN_INTERACTIVE_MODE == true ]; then
@@ -1038,7 +1038,7 @@ if [ ${#DELETE_FILES[@]} -gt 0 ]; then
 						RM_EXIT_STATUS=$?
 
 						if [ "$RM_EXIT_STATUS" -ne 0 ]; then
-							EXIT=$(( $EXIT | 16 ))
+							EXIT=$(($EXIT | 16))
 							echo "$APP_NAME: execution of \`$RM_CMD\` failed (exit status $RM_EXIT_STATUS)" >&2
 						fi
 					fi
